fragment UserFragment on User {
  id
  name
  lastName
  email
  username
  birthdate
  createdAt
  updatedAt
}

mutation AccountRegister($input: AccountRegisterInput!) {
  accountRegister(input: $input) {
    user {
      ...UserFragment
    }
    error {
      field
      message
      code
    }
  }
}
