fragment AccountRegisterErrorFragment on AccountRegisterError {
  code
  field
  message
}

fragment UserErrorFragment on UserError {
  code
  field
  message
}

fragment UserFragment on User {
  id
  name
  lastName
  email
  username
  birthdate
  gender
  pronoun
  customGender
  createdAt
  updatedAt
}

query Me {
  me {
    me {
      ...UserFragment
    }
    error {
      ...UserErrorFragment
    }
  }
}

mutation AccountRegister($input: AccountRegisterInput!) {
  accountRegister(input: $input) {
    user {
      ...UserFragment
    }
    error {
      ...AccountRegisterErrorFragment
    }
  }
}
