name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Generate GraphQL Schemas
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run gql:generate:publish

      - name: Build project
        run: npm run build
